from .CharacterMatcher import CharacterMatcher as Character
from model_experimental.matchers.SequenceMatcher import SequenceMatcher as Sequence
from model_experimental.matchers.NonSequenceMatcher import NonSequenceMatcher as NonSequence
from model_experimental.matchers.RangeMatcher import RangeMatcher as Range